[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin-contracts/=lib/interop-lib/vendor/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/createx/lib/openzeppelin-contracts/contracts/",
    "@solady/=lib/interop-lib/lib/solady/src/",
    "createx/=lib/createx/src/",
    "erc4626-tests/=lib/createx/lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/createx/lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "interop-lib/=lib/interop-lib/",
    "openzeppelin-contracts/=lib/createx/lib/openzeppelin-contracts/",
    "openzeppelin/=lib/createx/lib/openzeppelin-contracts/contracts/",
    "solady/=lib/createx/lib/solady/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
